//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigationBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavigationBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string NavigationMenu_Option {
            get {
                return ResourceManager.GetString("NavigationMenu_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 1.1.
        /// </summary>
        internal static string Topic1_1_Option {
            get {
                return ResourceManager.GetString("Topic1_1_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 1.2.
        /// </summary>
        internal static string Topic1_2_Option {
            get {
                return ResourceManager.GetString("Topic1_2_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 1.3.
        /// </summary>
        internal static string Topic1_3_Option {
            get {
                return ResourceManager.GetString("Topic1_3_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 1.
        /// </summary>
        internal static string Topic1_Option {
            get {
                return ResourceManager.GetString("Topic1_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 2.1.
        /// </summary>
        internal static string Topic2_1_Option {
            get {
                return ResourceManager.GetString("Topic2_1_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 2.2.
        /// </summary>
        internal static string Topic2_2_Option {
            get {
                return ResourceManager.GetString("Topic2_2_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 2.3.
        /// </summary>
        internal static string Topic2_3_Option {
            get {
                return ResourceManager.GetString("Topic2_3_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 2.
        /// </summary>
        internal static string Topic2_Option {
            get {
                return ResourceManager.GetString("Topic2_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 3.1.
        /// </summary>
        internal static string Topic3_1_Option {
            get {
                return ResourceManager.GetString("Topic3_1_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 3.2.
        /// </summary>
        internal static string Topic3_2_Option {
            get {
                return ResourceManager.GetString("Topic3_2_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 3.3.
        /// </summary>
        internal static string Topic3_3_Option {
            get {
                return ResourceManager.GetString("Topic3_3_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic 3.
        /// </summary>
        internal static string Topic3_Option {
            get {
                return ResourceManager.GetString("Topic3_Option", resourceCulture);
            }
        }
    }
}
